### ISSUE TITLE
Android Studio badge doesnt copy properly

### ISSUE THREAD

**Issue by ywaf** [Aveek-Saha/GitHub-Profile-Badges#1]
Hi,

When copying the android studio badge on ```https://home.aveek.io/GitHub-Profile-Badges/```, it copies as ```https://img.shields.io/badge/Android Studio-3DDC84.svg?style=for-the-badge&logo=Android-Studio&logoColor=white```, which has a space in the URL meaning that github wont take it as an image url, so it wont display. The correct formatting should have a _ between Android and Studio (```https://img.shields.io/badge/Android_Studio-3DDC84.svg?style=for-the-badge&logo=Android-Studio&logoColor=white```)

Thanks :)

**Comment by ywaf** [comment]
Actually this happens for every icon with a space in its name.

**Comment by Aveek-Saha** [comment]
Issue has been resolved with correct URI encoding

**Comment by ywaf** [comment]
Thanks :)
