### ISSUE TITLE
Add Lean and Dafny

### ISSUE THREAD

**Issue by jpoly1219** [Aveek-Saha/GitHub-Profile-Badges#4]
Hello, would it be possible to add badges for the Lean theorem prover (https://lean-lang.org) and Dafny (https://dafny.org)?
I'm thinking either black on white or white on black for lean, and yellow background with black text for Dafny.
Thank you!

**Comment by Aveek-Saha** [comment]
Hi, This app leverages [Simple Icons](https://github.com/simple-icons/simple-icons) for it's icons, that would be the appropriate repo for this icon request. Once the icon is added to simple icons and released it will automatically show up in this app.
